name: Build RetroArch + mGBA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your tools repo (if you need it for configs)
      - name: Checkout tooling repo
        uses: actions/checkout@v3

      # 2) Checkout RetroArch @ v1.9.0 (with submodules)
      - name: Checkout RetroArch v1.9.0
        uses: actions/checkout@v3
        with:
          repository: libretro/RetroArch
          ref: v1.9.0
          path: RetroArch
          submodules: recursive

      # 3) Install cross‐compiler and build tools
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential autoconf automake libtool pkg-config \
            curl gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf binutils

      # 4) Build RetroArch (fbdev, static)
      - name: Build RetroArch
        run: |
          cd RetroArch
          ./autogen.sh
          mkdir build && cd build
          ../configure \
            --host=arm-linux-gnueabihf \
            --disable-shared \
            --enable-static \
            --enable-fbdev \
            --disable-sdl \
            --disable-x \
            --disable-wayland \
            --disable-opengl \
            --disable-pulse \
            --disable-alsa \
            --disable-udev \
            --disable-usb \
            --disable-dynamic
          make -j$(nproc)
          strip retroarch
          mv retroarch $GITHUB_WORKSPACE/retroarch-armhf

      # 5) Build mGBA libretro core
      - name: Build mGBA core
        run: |
          git clone https://github.com/libretro/mgba.git mgba
          cd mgba
          make \
            CROSS_COMPILE=arm-linux-gnueabihf- \
            platform=unix-armv7-hardfloat-neon \
            STATIC=1 \
            -j$(nproc)
          strip mgba_libretro.so
          mv mgba_libretro.so $GITHUB_WORKSPACE/mgba-libretro.so

      # 6) Upload RetroArch binary
      - name: Upload RetroArch
        uses: actions/upload-artifact@v4
        with:
          name: retroarch-armhf
          path: retroarch-armhf

      # 7) Upload mGBA core
      - name: Upload mGBA core
        uses: actions/upload-artifact@v4
        with:
          name: mgba-libretro
          path: mgba-libretro.so
