name: Build RetroArch + mGBA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            autoconf automake libtool pkg-config build-essential \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf binutils

      - name: Build RetroArch v1.9.0
        run: |
          git clone https://github.com/libretro/RetroArch.git
          cd RetroArch
          git checkout v1.9.0
          git submodule update --init --recursive
          ./autogen.sh

          # run configure from the repo root so qb/ is found
          ./configure \
            --host=arm-linux-gnueabihf \
            --disable-shared \
            --enable-static \
            --enable-fbdev \
            --disable-sdl \
            --disable-x \
            --disable-wayland \
            --disable-opengl \
            --disable-pulse \
            --disable-alsa \
            --disable-udev \
            --disable-usb \
            --disable-dynamic

          make -j$(nproc)
          strip retroarch
          mv retroarch $GITHUB_WORKSPACE/retroarch-armhf

      - name: Build mGBA core
        run: |
          git clone https://github.com/libretro/mgba.git
          cd mgba
          make \
            CROSS_COMPILE=arm-linux-gnueabihf- \
            platform=unix-armv7-hardfloat-neon \
            STATIC=1 \
            -j$(nproc)
          strip mgba_libretro.so
          mv mgba_libretro.so $GITHUB_WORKSPACE/mgba-libretro.so

      - name: Upload RetroArch binary
        uses: actions/upload-artifact@v4
        with:
          name: retroarch-armhf
          path: retroarch-armhf

      - name: Upload mGBA core
        uses: actions/upload-artifact@v4
        with:
          name: mgba-libretro
          path: mgba-libretro.so
